version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${PUBLIC_PORT}:3000"
    entrypoint:
      - node
      - /app/dist/index
      - --config=/app/.config.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
