version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    extra_hosts:
      - "vega.fcyb.mirea.ru:192.168.71.199"
    env_file:
      - .env
    ports:
      - "${PUBLIC_PORT}:3000"
    restart: unless-stopped
    entrypoint:
      - node
      - /app/dist/index
      - --config=/app/.config.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
